import { useEffect } from "react";
import { useSelector } from "react-redux";

import Head from "next/head";

export default function GameDetail() {
  const dataGame = useSelector((state) => state.gameReducer);
  const gameDataDetail = dataGame.gameDetail;

  useEffect(() => {
    console.log(dataGame.gameDetail, "===============>asd");
  });

  return (
    <>
      <Head>
        <title>Game Detail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>GAME DETAIL</h1>
    </>
  );
}
