import Head from 'next/head';
import 'bootstrap/dist/css/bootstrap.css';
import { useEffect } from 'react';
// import 'bootstrap/dist/js/bootstrap';

export default function Home() {
  useEffect(() => {
    require('bootstrap/dist/js/bootstrap');
  }, []);

  return (
    <>
      <Head>
        <title>FSW 29</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container">
          <h1 className='text-center'>Hello Dek</h1>
        </div>
      </main>
    </>
  )
}
