import { useState, useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { useNavigate } from "react-router";

import Link from "next/link";
import Head from "next/head";


export default () => {

    let [dataUsers, setDataUsers]=useState();

    useEffect(() =>{
        fetchData();
    },[])

    

    const fetchData = async () =>{
        try{
            const data=await fetch('/api/profile/users')
            let dataGet=await data.json()

            setDataUsers(dataGet);
            console.log(dataGet,"===> data di profile.jsx")

        }catch(err){
            console.log(err)
        }
    }


    return(
        <>
            <Head>
                <title>Profile</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        
        </>
    )
}