import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { resetPassword } from "@/redux/actions/auth.action";
import { useRouter } from "next/router";

const ResetPasswordForm = () => {
  const [password, setPassword] = useState('');

  const dispatch = useDispatch();
  const {
    // loginUserLoading,
    resetPasswordFulfilled,
    resetPasswordLoading
  } = useSelector((state) =>  state.authReducer);
  // console.info(resetPasswordFulfilled, '=> reset password fulfilled');

  const router = useRouter();

  const handleUpdatePassword = (event) => {
    event.preventDefault();

    const code = new URLSearchParams(window.location.search).get("oobCode");
    const newPassword = password;
    // console.info(code, newPassword, '=> data code');

    const dataBody = {
      code, newPassword
    };

    dispatch(resetPassword(dataBody));

    alert('Your password has been successfully updated!');
    router.push('/login')
  }

  return (
    <>
      <Head>
        <title>Reset Password</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="h-100 bg-dark">
        <div className="container py-5 h-100">
          <div className="row d-flex justify-content-center align-items-center h-100">
            <div className="col">
              <div className="card card-registration my-4">
                <div className="row g-0">
                  <div className="col-xl-6 d-none d-xl-block">
                    <img
                      src="https://images.unsplash.com/photo-1542549237432-a176cb9d5e5e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=814&q=80"
                      alt="Sample photo"
                      className="img-fluid"
                      style={{
                        borderTopLeftRadius: ".25rem",
                        borderBottomLeftRadius: ".25rem"
                      }}
                    />
                  </div>
                  <div className="col-xl-6 justify-content-center align-items-center">
                    <div className="card-body p-md-5 text-black">
                      <h3 className="mb-5 text-uppercase text-center">
                        Update Password
                      </h3>
                      <form onSubmit={ handleUpdatePassword }>
                        <div className="mb-3">
                          <label htmlFor="password" className="form-label">New Password</label>
                          <input name="password" type="password" className="form-control" id="password" placeholder="New Password Address" onChange={ (e) => setPassword(e.target.value) } />
                        </div>
                        <div className="d-grid gap-2 mt-2">
                          <button type="submit" className="btn btn-primary">
                            {
                              resetPasswordLoading ? 'Process Update Password...' : 'Update Password'
                            }
                          </button>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}

export default ResetPasswordForm;
